// class metadate
export const CLASS_CONSTRUCTOR_METADATA_KEY = "XPROFILER::CLASS_CONSTRUCTOR";
export const CLASS_PROPS_KEY = "XPROFILER::CLASS_PROP";
export const CLASS_PROP_METATA_PREFIX = "XPROFILER::CLASS_PROP_METADATA::";

export const Scope = {
  SINGLETON: "XPROFILER::SINGLETON",
  EXECUTION: "XPROFILER::EXECUTION",
  TRANSIENT: "XPROFILER::TRANSIENT",
} as const;